@url_base=http://localhost:8000
@user={{url_base}}/user
@materia={{url_base}}/materias
@usuario_materia={{url_base}}/usuario_materia
@login={{url_base}}/login
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzU3MDI5MTM5fQ.gk6J741Mx19eRwYrBGDkiKJgr0HW7jYgXSnnCrLR7a8

### 🔐 LOGIN (obtenés el token)
POST {{login}}
Content-Type: application/x-www-form-urlencoded

username=nehuen@example.com
&password=2007

### 🧑‍🏫 CREAR USUARIO (profe o alumno)
POST {{user}}
Content-Type: application/json

{
    "nombre": "nehuen",
    "apellido": "ricardi",
    "mail": "nehuen@example.com",
    "contrasena": "2007",
    "is_profe": true,
    "dni": "47786443"
}


### 📚 CREAR MATERIA (solo profesor, requiere token)
POST {{materia}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "nombre_materia": "Quimica"
}

### 🔍 LISTAR TODAS LAS MATERIAS
GET {{materia}}

### 🔍 OBTENER MATERIA POR ID
GET {{materia}}/1


###ACTUALIZAR MATERIA (solo profesor)
PUT {{materia}}/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "nombre_materia": "Geografia"
}

### ELIMINAR MATERIA (solo profesor)
DELETE {{materia}}/1
Authorization: Bearer {{access_token}}

### 🔗 ASIGNAR MATERIA A USUARIO (solo profesor)
POST {{usuario_materia}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "id_usuario": 3,
    "id_materia": 2
}

### 📋 LISTAR MATERIAS DE UN USUARIO (protegido)
GET {{url_base}}/usuario/3/materias
Authorization: Bearer {{access_token}}
